services:
  - docker

before_install:
  - docker pull dials/test:3

script:
  - docker run dials/test:3 /bin/sh -c "pwd; ls -la; source build/setpaths.sh ; cd build; make reconf; cd ../modules/dxtbx; pytest --regression -n auto"
